CREATE TABLE player (
    PLAYER_ID BIGINT UNSIGNED NOT NULL,
    PLAYER_NAME VARCHAR(45) NOT NULL,
    WINS INT UNSIGNED NULL DEFAULT 0,
    LOSSES INT UNSIGNED NULL DEFAULT 0,
    FASTEST_TIME TIME NULL DEFAULT NULL,
    PRIMARY KEY (PLAYER_ID),
    UNIQUE KEY PLAYER_NAME_UNIQUE (PLAYER_NAME)
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb3;